@startuml

' ' |#AliceBlue|__SE課__|
' |__SE課__|
' :製作仕様書(基本編);

|#AntiqueWhite|__制御設計課(担当者)__|
group 引継ぎ
    start
    :製作仕様書(基本編)精査;
    note left
        SE課から受領した
        基本編仕様書を精査する
    end note

    :引継ぎＤＲ;
    note left
        SE課/機械設計/ソフト
        担当者参加
        不明点の洗い出し
        取り決め
    end note
    end group

    group キックオフ
        group 製本
            :バインダーの用意;
            :製本の背表紙を作成;
            note left
                リンク有
            end note
            end group

            :??書作成;
            note left
                リンク有
            end note
            :???書作成;
            note left
                リンク有
            end note
            :電力計算書作成;
            note left
                リンク有
            end note
            end group

            -> 3文書を提出;
            |#AquaMarine|__制御設計課(上長)__|
            :査閲;
            |#AntiqueWhite|__制御設計課(担当者)__|
            :製本ファイルに閉じる;
            group 協力会社依頼
                :協力会社の選定;
                :見積依頼書作成;
                :Mailにて依頼;

                note left
                    レイアウト図
                    ----
                    仕様書
                    ----
                    を添付
                end note

                end group
                fork

                    group 材料表1作成　　　　　
                        |#AntiqueWhite|__制御設計課(担当者)__|
                        :材料を抽出;
                        end group
                        forkagain
                        |__協力会社__|
                        :見積開始;
                        :外形図作成;
                        :展開図作成;
                        |#AntiqueWhite|__制御設計課(担当者)__|
                        end fork
                    end








                    ' if (出荷品が) then (ない)

                    ' |会員|
                    ' :願い下げ;
                    ' end
                    ' else (ある)
                    ' -> 承認が下りたことを伝える（PDFをメール添付);
                    ' :予約図書を受け取る;

                    ' |__出荷部門__|
                    '     :出荷する;
                    '     fork
                    '     :出荷を報告する;

                    ' |#AntiqueWhite|__経理部門__|
                    '     :請求する;

                    ' |__顧客__|
                    '     forkagain
                    '     :商品を受け取る;

                    ' |__顧客__|
                    '     end fork
                    '     :支払う;

                    ' |#AntiqueWhite|__経理部門__|
                    '     :入金を確認する;
                    '     stop

                    @enduml